### ISSUE TITLE
"ck install package:lib-qiskit" fails with LLVM v3.8

### ISSUE THREAD

**Issue by psyhtest** [ctuning/ck-qiskit#1]
Installing `package:lib-qiskit` fails with LLVM:
```
$ ck install package:lib-qiskit
...
/usr/bin/clang-3.8 -c  -std=c++14 -fopenmp -O3 -march=native -ffast-math -I./ -I./backends -I./engines -I./utilities -I./third-party -I./third-party/headers -pedantic -Wall -Wextra -Wfloat-equal -Wundef -Wcast-align -Wwrite-strings -Wmissing-declarations -Wredundan
t-decls -Wshadow -Woverloaded-virtual  -o ../../../out/main.o main.cpp
In file included from main.cpp:30:
In file included from ./simulator.hpp:28:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/random:38:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/cmath:45:
In file included from /usr/include/math.h:83:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:63:1: error: expected an OpenMP directive
__MATHCALL_VEC (cos,, (_Mdouble_ __x));
^
/usr/include/math.h:58:3: note: expanded from macro '__MATHCALL_VEC'
  __SIMD_DECL (__MATH_PRECNAME (function, suffix)) \
  ^
/usr/include/math.h:55:31: note: expanded from macro '__SIMD_DECL'
#define __SIMD_DECL(function) __CONCAT (__DECL_SIMD_, function)
                              ^
/usr/include/x86_64-linux-gnu/sys/cdefs.h:88:23: note: expanded from macro '__CONCAT'
#define __CONCAT(x,y)   x ## y
                        ^
note: (skipping 1 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)

...

<scratch space>:7:6: note: expanded from here
 omp declare simd notinbranch
     ^
In file included from main.cpp:30:
./simulator.hpp:35:10: fatal error: 'omp.h' file not found
#include <omp.h> // OpenMP
         ^
13 errors generated.
```
In the worst case, we can deal with this as in `src/qiskit-simulator/src/Makefile`:
```
# Check if compiler is Apple LLVM and doesn't support OpenMP
APPLELLVM = $(shell ${CC} --version | grep ^Apple)
ifeq ($(APPLELLVM),)
        CPPFLAGS = $(USER_FLAGS) -std=c++14 -fopenmp $(OPT) $(INCLUDE) $(WARNINGS)
else
        CPPFLAGS = $(USER_FLAGS) -std=c++14 $(OPT) $(INCLUDE) $(WARNINGS)
endif
```
Or we can provide a custom build script.

**Comment by psyhtest** [comment]
See also my rather lame attempt to specify the compiler [here](https://github.com/ctuning/ck-qiskit/blob/master/package/lib-qiskit/scripts.linux/install.sh#L48):
```
cd ${INSTALL_DIR}/src/src/qiskit-simulator/
make # CC=${CK_CC_PATH_FOR_CMAKE} CXX=${CK_CXX_PATH_FOR_CMAKE}
```
(It's lame in the sense that it leads to linking failures.)

**Comment by psyhtest** [comment]
It turns out that it fails only with LLVM v3.8 but compiles fine with v4.0 and v5.0
```
$ ck show env --tags=llvm  
Env UID:         Target OS: Bits: Name:         Version:               Tags:

a88c0e7e42e38654   linux-64    64 LLVM compiler 5.0.0-3~16.04.1        64bits,compiler,host-os-linux-64,lang-c,lang-cpp,llvm,target-os-linux-64,v5,v5.0,v5.0.0,v5.0.0.0,v5.0.0.0.4,v5.0.0.0.4.1
dee4bb9b7eb745bb   linux-64    64 LLVM compiler 4.0.0-1ubuntu1~16.04.2 64bits,compiler,host-os-linux-64,lang-c,lang-cpp,llvm,target-os-linux-64,v4,v4.0,v4.0.0,v4.0.0.0,v4.0.0.0.4,v4.0.0.0.4.2
281d477450533ad0   linux-64    64 LLVM compiler 3.8.0-2ubuntu4         64bits,compiler,host-os-linux-64,lang-c,lang-cpp,llvm,target-os-linux-64,v3,v3.8,v3.8.0,v3.8.0.0

$ ck show env --tags=lib,qiskit,compiled-by-llvm
Env UID:         Target OS: Bits: Name:               Version:       Tags:

cae145628fed4008   linux-64    64 Qiskit (built, cpu) master-4164a2c 64bits,compiled-by-llvm,compiled-by-llvm-4.0.0-1ubuntu1~16.04.2,host-os-linux-64,lib,qiskit,qiskit-sdk-py,quantum,target-os-linux-64,v0,v0.0,vcpu
57af39d862b26795   linux-64    64 Qiskit (built, cpu) master-4164a2c 64bits,compiled-by-llvm,compiled-by-llvm-5.0.0-3~16.04.1,host-os-linux-64,lib,qiskit,qiskit-sdk-py,quantum,target-os-linux-64,v0,v0.0,vcpu
```
As a workaround, we can specify the minimum version as 4, which should work also for all the versions of GCC and ICC in use.

**Comment by ens-lg4** [comment]
Please see my commit https://github.com/ctuning/ck-qiskit/commit/e510c7697a0736cf6a793b8a8ade815c521dc28a as one way to solve it (as @psyhtest  suggested, it excludes any compiler with version before 4.0.0)

**Comment by psyhtest** [comment]
Closing as we have a workaround now.
